export interface ISpaEnvResponse {
    SPA_ENV_MSP_MAINTENANCE_FLAG: string;
    SPA_ENV_MSP_MAINTENANCE_MESSAGE: string;
    SPA_ENV_ACL_MAINTENANCE_FLAG: string;
    SPA_ENV_ACL_MAINTENANCE_MESSAGE: string;
    SPA_ENV_PACUTOFF_MAINTENANCE_START: string;
}