#!/usr/bin/env bash
date
echo \$RETENTION_MONTH=$RETENTION_MONTH
curl -XDELETE http://elasticsearch:9200/logstash-`date -d "-$((${RETENTION_MONTH-3} + 1)) month" +%Y.%m`*
curl -XDELETE "http://localhost:9200/_snapshot/my_backup/snapshot_`date +%u`?pretty"
curl -XPUT "http://localhost:9200/_snapshot/my_backup/snapshot_`date +%u`?wait_for_completion=true&pretty"
