apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: 2018-02-07T00:28:34Z
  labels:
    build: msp-1.3-prototype-build-angular-app-build
  name: msp-1.3-prototype-build-angular-app-build
  namespace: gcpe-mygovbc-msp-demo
  selfLink: /oapi/v1/namespaces/gcpe-mygovbc-msp-demo/buildconfigs/msp-1.3-prototype-build-angular-app-build
  uid: d4db3523-0b9d-11e8-b39a-0050568348bb
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: msp-1.3-prototype-build-angular-app:latest
  postCommit: {}
  resources:
    limits:
      cpu: "1"
      memory: 4Gi
    requests:
      memory: 2Gi
  runPolicy: Serial
  source:
    git:
      ref: 1.3-prototype
      uri: https://github.com/bcgov/MyGovBC-MSP.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:6
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
  - imageChange:
      lastTriggeredImageID: registry.access.redhat.com/rhscl/nodejs-6-rhel7@sha256:11339ae61f556fe5568ff12c738a4916f1d0d58653b83ed2f6b6e52bbb68a2af
    type: ImageChange
status:
  lastVersion: 5
